// examples/vue/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import { DXFViewer, parseDxf } from "dxf-vuer";
import type { DxfData } from "dxf-vuer";
import "dxf-vuer/style.css";

const dxfData = ref<DxfData | null>(null);
const fileName = ref("");

async function handleFile(e: Event) {
  const file = (e.target as HTMLInputElement).files?.[0];
  if (!file) return;
  fileName.value = file.name;
  const text = await file.text();
  dxfData.value = parseDxf(text);
}
</script>

<template>
  <div style="font-family: system-ui, sans-serif">
    <div style="padding: 16px; display: flex; gap: 12px; align-items: center">
      <label style="padding: 8px 16px; background: #fff; border: 1px solid #ccc; border-radius: 6px; cursor: pointer; font-size: 14px">
        Open DXF file
        <input type="file" accept=".dxf" hidden @change="handleFile" />
      </label>
      <span v-if="fileName" style="font-size: 14px; color: #666">{{ fileName }}</span>
    </div>

    <DXFViewer
      v-if="dxfData"
      :dxf-data="dxfData"
      :file-name="fileName"
      :show-reset-button="true"
      :show-coordinates="true"
      style="height: calc(100vh - 60px)"
    />

    <div
      v-else
      style="
        display: flex;
        align-items: center;
        justify-content: center;
        height: calc(100vh - 60px);
        color: #999;
        font-size: 18px;
      "
    >
      Select a .dxf file to render
    </div>
  </div>
</template>

// examples/react/src/App.tsx
import { useState } from "react";
import { DxfViewer } from "./DxfViewer";

export function App() {
  const [dxfText, setDxfText] = useState<string | null>(null);
  const [fileName, setFileName] = useState("");

  function handleFile(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    setFileName(file.name);
    const reader = new FileReader();
    reader.onload = () => setDxfText(reader.result as string);
    reader.readAsText(file);
  }

  return (
    <div style={{ fontFamily: "system-ui, sans-serif" }}>
      <div style={{ padding: 16, display: "flex", gap: 12, alignItems: "center" }}>
        <label
          style={{
            padding: "8px 16px",
            background: "#fff",
            border: "1px solid #ccc",
            borderRadius: 6,
            cursor: "pointer",
            fontSize: 14,
          }}
        >
          Open DXF file
          <input type="file" accept=".dxf" onChange={handleFile} hidden />
        </label>
        {fileName && <span style={{ fontSize: 14, color: "#666" }}>{fileName}</span>}
      </div>

      {dxfText ? (
        <DxfViewer dxfText={dxfText} />
      ) : (
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            height: "calc(100vh - 60px)",
            color: "#999",
            fontSize: 18,
          }}
        >
          Select a .dxf file to render
        </div>
      )}
    </div>
  );
}
