// packages/dxf-vuer/src/components/FileUploader.vue
<template>
  <div class="dxfk-file-uploader">
    <label for="dxf-file-input" class="dxfk-file-input-label">
      <input
        id="dxf-file-input"
        type="file"
        accept=".dxf"
        class="dxfk-file-input"
        aria-label="Select a DXF file to load"
        @change="handleFileChange"
      />
      <div class="dxfk-file-uploader-button">
        <svg
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
        >
          <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
          <polyline points="17 8 12 3 7 8" />
          <line x1="12" y1="3" x2="12" y2="15" />
        </svg>
        <span>Load DXF File</span>
      </div>
    </label>
  </div>
</template>

<script setup lang="ts">
interface Emits {
  (e: "file-selected", file: File): void;
}

const emit = defineEmits<Emits>();

const handleFileChange = (event: Event) => {
  const target = event.target as HTMLInputElement;
  const file = target.files?.[0];

  if (file) {
    emit("file-selected", file);
  }
  // Reset value so re-selecting the same file triggers a change event
  target.value = "";
};
</script>

<style scoped>
.dxfk-file-uploader {
  display: flex;
  flex-direction: column;
  gap: var(--dxfk-spacing-sm, 8px);
  flex: 1;
  max-width: 420px;
}

.dxfk-file-input {
  display: none;
}

.dxfk-file-input-label {
  cursor: pointer;
}

.dxfk-file-uploader-button {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: var(--dxfk-spacing-sm, 8px);
  padding: var(--dxfk-spacing-sm, 8px) var(--dxfk-spacing-md, 16px);
  background-color: rgba(255, 255, 255, 0.2);
  color: white;
  border: 1px solid rgba(255, 255, 255, 0.3);
  border-radius: var(--dxfk-border-radius, 4px);
  font-weight: 500;
  font-size: 14px;
  transition: all 0.2s;
  user-select: none;
  backdrop-filter: blur(10px);
}

.dxfk-file-uploader-button:hover {
  background-color: rgba(255, 255, 255, 0.3);
  border-color: rgba(255, 255, 255, 0.5);
}

.dxfk-file-uploader-button:active {
  transform: scale(0.98);
}

@media (max-width: 768px) {
  .dxfk-file-uploader-button {
    padding: var(--dxfk-spacing-sm, 8px);
    justify-content: center;
  }
}
</style>

// packages/dxf-react/src/components/FileUploader.tsx
import type { ChangeEvent } from "react";

export interface FileUploaderProps {
  /** Fired with the selected `.dxf` File. */
  onFileSelected?: (file: File) => void;
}

import "./FileUploader.css";

/**
 * A simple `.dxf` file picker button. Resets its value after each selection so
 * re-selecting the same file fires `onFileSelected` again.
 */
export function FileUploader({ onFileSelected }: FileUploaderProps) {
  const handleFileChange = (event: ChangeEvent<HTMLInputElement>) => {
    const target = event.target;
    const file = target.files?.[0];
    if (file) onFileSelected?.(file);
    // Reset value so re-selecting the same file triggers a change event.
    target.value = "";
  };

  return (
    <div className="dxfk-file-uploader">
      <label htmlFor="dxf-file-input" className="dxfk-file-input-label">
        <input
          id="dxf-file-input"
          type="file"
          accept=".dxf"
          className="dxfk-file-input"
          aria-label="Select a DXF file to load"
          onChange={handleFileChange}
        />
        <div className="dxfk-file-uploader-button">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
            <polyline points="17 8 12 3 7 8" />
            <line x1="12" y1="3" x2="12" y2="15" />
          </svg>
          <span>Load DXF File</span>
        </div>
      </label>
    </div>
  );
}
